# Generated by Django 2.2.7 on 2019-12-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_target', models.CharField(max_length=30)),
                ('rep_content', models.TextField(max_length=1000)),
                ('rep_date', models.DateTimeField(verbose_name='time')),
                ('rep_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_s', to='User.HUser')),
            ],
        ),
    ]
