# Generated by Django 2.2.7 on 2019-12-05 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('skku', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worked_s', to='User.HUser')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worked_t', to='User.HUser')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_male', models.BooleanField(default=True)),
                ('age', models.IntegerField(default=0)),
                ('intro', models.CharField(default='안녕', max_length=40)),
                ('subj', models.CharField(default='', max_length=80)),
                ('region', models.CharField(default='', max_length=80)),
                ('score', models.FloatField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('dep', models.CharField(default='과', max_length=40)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.HUser')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('content', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_s', to='User.HUser')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_t', to='User.HUser')),
            ],
        ),
        migrations.CreateModel(
            name='Eval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('details', models.CharField(default='', max_length=40)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='my_eval', to='User.HUser')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='User.HUser')),
            ],
        ),
    ]
